package view;

import Connectivity.Dbmanager;
import Connectivity.QueryManager;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import model.Baggage;
import model.CreateAccount;
import model.Customerinfo;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author JasperKapper >= Kavehskapper
 */
public class Admin extends javax.swing.JFrame {

    private ArrayList<CreateAccount> udl = new ArrayList();
    private int userId = 0;

    int xMouse, yMouse;
 public void SetInfo(CreateAccount createaccount) {
        Name.setText("Logged in as: " +createaccount.accounttype);
        usernameAdminText.setText(createaccount.username);
        welcomeAdmin.setText("Welcome " + createaccount.username+ "," );
        nameAdminText.setText("Not Set");
        usernameAdminText.setText("Not Set");
        addressAdminText.setText("Not Set");
        dateAdminText.setText("Not Set");
        postalcodeAdminText.setText("Not Set");
        cityAdminText.setText("Not Set");
        emailAdminText.setText("Not Set");
 }
    
    public void SetUser(CreateAccount createaccount) {

        if ("admin".equals(createaccount.accounttype)) {
            setVisible(true);
        } else {
            setVisible(false);
        }
    }

    public Admin() {
        super("Lost Baggage");
        setSize(1300, 650);
        setResizable(false);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        initComponents();

        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(AdminHome);
        jPanel1.repaint();
        jPanel1.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel18 = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Home = new javax.swing.JPanel();
        AdminHome = new javax.swing.JPanel();
        welcomeAdmin = new javax.swing.JLabel();
        profileAdmin = new javax.swing.JLabel();
        nameAdmin = new javax.swing.JLabel();
        nameAdminText = new javax.swing.JLabel();
        usernameAdmin = new javax.swing.JLabel();
        usernameAdminText = new javax.swing.JLabel();
        addressAdmin = new javax.swing.JLabel();
        addressAdminText = new javax.swing.JLabel();
        dateAdmin = new javax.swing.JLabel();
        dateAdminText = new javax.swing.JLabel();
        cityAdmin = new javax.swing.JLabel();
        cityAdminText = new javax.swing.JLabel();
        postalcodeAdmin = new javax.swing.JLabel();
        postalcodeAdminText = new javax.swing.JLabel();
        countryAdmin = new javax.swing.JLabel();
        countryAdminText = new javax.swing.JLabel();
        emailAdmin = new javax.swing.JLabel();
        emailAdminText = new javax.swing.JLabel();
        editAdminButton = new javax.swing.JToggleButton();
        BackgroundAdmin = new javax.swing.JLabel();
        Edit = new javax.swing.JPanel();
        AdminEdit = new javax.swing.JPanel();
        corendonTitleEdit = new javax.swing.JLabel();
        zipEdit = new javax.swing.JLabel();
        countryEdit = new javax.swing.JLabel();
        addressEdit = new javax.swing.JLabel();
        cityEdit = new javax.swing.JLabel();
        nameEdit = new javax.swing.JLabel();
        emailEdit = new javax.swing.JLabel();
        addressFieldEdit = new javax.swing.JTextField();
        cityFieldEdit = new javax.swing.JTextField();
        zipFieldEdit = new javax.swing.JTextField();
        emailFieldEdit = new javax.swing.JTextField();
        nameFieldEdit = new javax.swing.JTextField();
        countryFieldEdit = new javax.swing.JTextField();
        accountInfoTitleEdit = new javax.swing.JLabel();
        repeatwwFieldEdit = new javax.swing.JTextField();
        accountypeEdit = new javax.swing.JLabel();
        repeatwwEdit = new javax.swing.JLabel();
        newwwEdit = new javax.swing.JLabel();
        newwwFieldEdit = new javax.swing.JTextField();
        oldwwFieldEdit = new javax.swing.JTextField();
        oldwwEdit = new javax.swing.JLabel();
        newusernameEdit = new javax.swing.JLabel();
        newusernameFieldEdit = new javax.swing.JTextField();
        PersonalInfoTitleEdit = new javax.swing.JLabel();
        accounttypeDropboxEdit = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        background = new javax.swing.JLabel();
        AdminEdit1 = new javax.swing.JPanel();
        corendonTitleEdit1 = new javax.swing.JLabel();
        PersonalInfoTitleEdit1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        searchtxt = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listUsers = new javax.swing.JList();
        jButton7 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        background1 = new javax.swing.JLabel();
        Create = new javax.swing.JPanel();
        AdminCreate = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        homeadress = new javax.swing.JTextField();
        homecity = new javax.swing.JTextField();
        homepostal = new javax.swing.JTextField();
        homeemail = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();
        homecountry = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        accounttypee = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        password2 = new javax.swing.JPasswordField();
        password = new javax.swing.JPasswordField();
        username1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Help = new javax.swing.JPanel();
        AdminHelp = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel5 = new javax.swing.JLabel();
        Delete = new javax.swing.JPanel();
        AdminDelete = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        menu1 = new javax.swing.JPanel();
        homeButton1 = new javax.swing.JLabel();
        editButton = new javax.swing.JLabel();
        createButton = new javax.swing.JLabel();
        helpButton = new javax.swing.JLabel();
        logoutKnop = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        jLabel18.setText("Date of birth :");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lost Baggage");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Name.setText("Logged in as:");
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 150, 30));

        ID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ID.setText("Employee ID:");
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 130, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 9));
        jPanel1.setLayout(new java.awt.BorderLayout());

        Home.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 9));
        Home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminHome.setBackground(new java.awt.Color(153, 51, 51));
        AdminHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        AdminHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeAdmin.setFont(new java.awt.Font("Tahoma", 2, 30)); // NOI18N
        welcomeAdmin.setText("Welcome, ");
        AdminHome.add(welcomeAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 310, 50));

        profileAdmin.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        profileAdmin.setText("Profile :");
        AdminHome.add(profileAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 90, 40));

        nameAdmin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nameAdmin.setText("Name :");
        AdminHome.add(nameAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 90, 20));

        nameAdminText.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        nameAdminText.setText("example: John");
        AdminHome.add(nameAdminText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 90, 20));

        usernameAdmin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        usernameAdmin.setText("Username :");
        AdminHome.add(usernameAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 90, 20));

        usernameAdminText.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        usernameAdminText.setText("example: JohnS001");
        AdminHome.add(usernameAdminText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 100, 20));

        addressAdmin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addressAdmin.setText("Address :");
        AdminHome.add(addressAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 90, 20));

        addressAdminText.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        addressAdminText.setText("example: Duivendrechtsekade 44");
        AdminHome.add(addressAdminText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 170, 20));

        dateAdmin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dateAdmin.setText("Date :");
        AdminHome.add(dateAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 90, 20));

        dateAdminText.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        dateAdminText.setText("example: 01.10.2014");
        AdminHome.add(dateAdminText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 110, 20));

        cityAdmin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cityAdmin.setText("City :");
        AdminHome.add(cityAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 90, 20));

        cityAdminText.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        cityAdminText.setText("example: Amsterdam");
        AdminHome.add(cityAdminText, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 110, 20));

        postalcodeAdmin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        postalcodeAdmin.setText("Postal code :");
        AdminHome.add(postalcodeAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 90, 20));

        postalcodeAdminText.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        postalcodeAdminText.setText("example: 1096AH");
        AdminHome.add(postalcodeAdminText, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 90, 20));

        countryAdmin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        countryAdmin.setText("Country :");
        AdminHome.add(countryAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 90, 20));

        countryAdminText.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        countryAdminText.setText("example: The Netherlands");
        AdminHome.add(countryAdminText, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 130, 20));

        emailAdmin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        emailAdmin.setText("Email :");
        AdminHome.add(emailAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 90, 20));

        emailAdminText.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        emailAdminText.setText("example: John.S@corendon.nl");
        AdminHome.add(emailAdminText, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 150, 20));

        editAdminButton.setText("Edit");
        editAdminButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editAdminButtonMouseClicked(evt);
            }
        });
        editAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAdminButtonActionPerformed(evt);
            }
        });
        AdminHome.add(editAdminButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, -1, -1));

        BackgroundAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/00000001.JPG"))); // NOI18N
        BackgroundAdmin.setToolTipText("");
        BackgroundAdmin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        AdminHome.add(BackgroundAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 490));

        Home.add(AdminHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(Home, java.awt.BorderLayout.CENTER);

        Edit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 9));
        Edit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminEdit.setBackground(new java.awt.Color(153, 51, 51));
        AdminEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        AdminEdit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        corendonTitleEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/corendon-airlines.jpg"))); // NOI18N
        corendonTitleEdit.setText("jLabel11");
        AdminEdit.add(corendonTitleEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 300, 70));

        zipEdit.setText("Zip/Postal code   :");
        AdminEdit.add(zipEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 90, 20));

        countryEdit.setText("Country    :");
        AdminEdit.add(countryEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 70, 20));

        addressEdit.setText("Address   :");
        AdminEdit.add(addressEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 60, 20));

        cityEdit.setText("City     :");
        AdminEdit.add(cityEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, -1, -1));

        nameEdit.setText("Name   :");
        AdminEdit.add(nameEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, 20));

        emailEdit.setText("Email     :");
        AdminEdit.add(emailEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, -1, -1));

        addressFieldEdit.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        addressFieldEdit.setText("Example: Egidiusstraat");
        addressFieldEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressFieldEditActionPerformed(evt);
            }
        });
        AdminEdit.add(addressFieldEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 240, -1));

        cityFieldEdit.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        cityFieldEdit.setText("Example: Amsterdam");
        AdminEdit.add(cityFieldEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 240, -1));

        zipFieldEdit.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        zipFieldEdit.setText("Example: 1055GK");
        AdminEdit.add(zipFieldEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 240, -1));

        emailFieldEdit.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        emailFieldEdit.setText("Example: John@corendon.com");
        AdminEdit.add(emailFieldEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 240, -1));

        nameFieldEdit.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        nameFieldEdit.setText("example: john");
        AdminEdit.add(nameFieldEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 240, -1));

        countryFieldEdit.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        countryFieldEdit.setText("Example: The Netherlands");
        AdminEdit.add(countryFieldEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 240, -1));

        accountInfoTitleEdit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        accountInfoTitleEdit.setText("Account information:");
        AdminEdit.add(accountInfoTitleEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        repeatwwFieldEdit.setText("***********");
        AdminEdit.add(repeatwwFieldEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 240, -1));

        accountypeEdit.setText("Account type     :");
        AdminEdit.add(accountypeEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 100, -1));

        repeatwwEdit.setText(" repeat password  :");
        AdminEdit.add(repeatwwEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 100, 20));

        newwwEdit.setText("New Password   :");
        AdminEdit.add(newwwEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 90, 20));

        newwwFieldEdit.setText("***********");
        AdminEdit.add(newwwFieldEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 240, -1));

        oldwwFieldEdit.setText("***********");
        oldwwFieldEdit.setToolTipText("");
        AdminEdit.add(oldwwFieldEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 240, -1));

        oldwwEdit.setText("Old Password  :");
        AdminEdit.add(oldwwEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        newusernameEdit.setText("New Username :");
        AdminEdit.add(newusernameEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 100, 20));

        newusernameFieldEdit.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        newusernameFieldEdit.setText("Example: Administrator1988");
        AdminEdit.add(newusernameFieldEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 240, -1));

        PersonalInfoTitleEdit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PersonalInfoTitleEdit.setText("Personal information:");
        AdminEdit.add(PersonalInfoTitleEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, -1, -1));

        accounttypeDropboxEdit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manager", "Administrator", "Employee" }));
        AdminEdit.add(accounttypeDropboxEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 240, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Vliegtuig_CorendonNL-2-stijgend.png"))); // NOI18N
        AdminEdit.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 160, 50));

        jButton3.setText("Save ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        AdminEdit.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/00000001.JPG"))); // NOI18N
        background.setToolTipText("");
        background.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        AdminEdit.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 450));

        Edit.add(AdminEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        AdminEdit1.setBackground(new java.awt.Color(153, 51, 51));
        AdminEdit1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        AdminEdit1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        corendonTitleEdit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/corendon-airlines.jpg"))); // NOI18N
        corendonTitleEdit1.setText("jLabel11");
        AdminEdit1.add(corendonTitleEdit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 300, 70));

        PersonalInfoTitleEdit1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PersonalInfoTitleEdit1.setText("Edit account");
        AdminEdit1.add(PersonalInfoTitleEdit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Vliegtuig_CorendonNL-2-stijgend.png"))); // NOI18N
        AdminEdit1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 160, 50));

        jButton4.setText("Select");
        AdminEdit1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        jButton5.setText("Edit Personal information");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton5KeyPressed(evt);
            }
        });
        AdminEdit1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 170, -1));

        searchtxt.setText("jTextField5");
        AdminEdit1.add(searchtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 290, -1));

        jButton6.setText("Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        AdminEdit1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        jScrollPane2.setToolTipText("");

        jScrollPane2.setViewportView(listUsers);

        AdminEdit1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 290, 180));

        jButton7.setText("Delete");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        AdminEdit1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, -1));

        jLabel4.setText("Password :");
        AdminEdit1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 70, 20));

        jTextField4.setText("jTextField4");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        AdminEdit1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, 160, -1));

        jLabel6.setText("Accounttype :");
        AdminEdit1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 80, 20));

        jLabel7.setText("Username :");
        AdminEdit1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 70, 20));

        jTextField6.setText("jTextField4");
        AdminEdit1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, 160, -1));

        jTextField7.setText("jTextField4");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        AdminEdit1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 160, -1));

        jButton8.setText("Edit");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        AdminEdit1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 60, -1));

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/00000001.JPG"))); // NOI18N
        background1.setToolTipText("");
        background1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        AdminEdit1.add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 450));

        Edit.add(AdminEdit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(Edit, java.awt.BorderLayout.PAGE_START);

        Create.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 9));
        Create.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminCreate.setBackground(new java.awt.Color(153, 51, 51));
        AdminCreate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        AdminCreate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/corendon-airlines.jpg"))); // NOI18N
        jLabel31.setText("jLabel11");
        AdminCreate.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 300, 70));

        jLabel32.setText("Zip/Postal code   :");
        AdminCreate.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 90, 20));

        jLabel33.setText("Country    :");
        AdminCreate.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 70, 20));

        jLabel34.setText("Address   :");
        AdminCreate.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 60, 20));

        jLabel35.setText("City     :");
        AdminCreate.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, -1, -1));

        jLabel36.setText("Name   :");
        AdminCreate.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, 20));

        jLabel37.setText("Email     :");
        AdminCreate.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, -1, -1));

        homeadress.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        homeadress.setText("Example: Egidiusstraat");
        homeadress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeadressActionPerformed(evt);
            }
        });
        AdminCreate.add(homeadress, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 240, -1));

        homecity.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        homecity.setText("Example: Amsterdam");
        homecity.setToolTipText("");
        AdminCreate.add(homecity, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 240, -1));

        homepostal.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        homepostal.setText("Example: 1055GK");
        AdminCreate.add(homepostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 240, -1));

        homeemail.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        homeemail.setText("Example: John@corendon.com");
        AdminCreate.add(homeemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 240, -1));

        firstname.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        firstname.setText("example: john");
        AdminCreate.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 240, -1));

        homecountry.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        homecountry.setText("Example: The Netherlands");
        AdminCreate.add(homecountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 240, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel38.setText("Account information:");
        AdminCreate.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        jLabel39.setText("Account type     :");
        AdminCreate.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 100, -1));

        jLabel40.setText(" repeat password  :");
        AdminCreate.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 100, 20));

        jLabel41.setText("New Password   :");
        AdminCreate.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 90, 20));

        jLabel43.setText("New Username :");
        AdminCreate.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 110, 20));

        accounttypee.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        accounttypee.setText("Manager,Employee,Admin");
        accounttypee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accounttypeeActionPerformed(evt);
            }
        });
        AdminCreate.add(accounttypee, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 240, -1));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel45.setText("Personal information:");
        AdminCreate.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Vliegtuig_CorendonNL-2-stijgend.png"))); // NOI18N
        AdminCreate.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 160, 50));

        jLabel3.setText("Date of birth :");
        AdminCreate.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, -1, -1));

        jSpinner2.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.YEAR));
        AdminCreate.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 150, 20));

        jButton2.setText("Save & Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        AdminCreate.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, -1));

        password2.setText("jPasswordField1");
        password2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        password2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password2ActionPerformed(evt);
            }
        });
        AdminCreate.add(password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 240, 20));

        password.setText("jPasswordField1");
        password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        AdminCreate.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 240, 20));

        username1.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        username1.setText("Example: Adminstrator1981");
        username1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username1ActionPerformed(evt);
            }
        });
        AdminCreate.add(username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 240, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/00000001.JPG"))); // NOI18N
        jLabel9.setToolTipText("");
        jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        AdminCreate.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 450));

        Create.add(AdminCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(Create, java.awt.BorderLayout.LINE_END);

        Help.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 9));
        Help.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminHelp.setBackground(new java.awt.Color(153, 51, 51));
        AdminHelp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.gray, null, java.awt.Color.lightGray));
        AdminHelp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/corendon-airlines.jpg"))); // NOI18N
        jLabel17.setText("jLabel11");
        AdminHelp.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 300, 70));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Vliegtuig_CorendonNL-2-stijgend.png"))); // NOI18N
        AdminHelp.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 160, 50));

        jLabel52.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel52.setText("Download PDF: ");
        AdminHelp.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));
        AdminHelp.add(jFileChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, 270));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/00000001.JPG"))); // NOI18N
        jLabel5.setToolTipText("");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        AdminHelp.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 971, 482));

        Help.add(AdminHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 490));

        jPanel1.add(Help, java.awt.BorderLayout.LINE_START);

        Delete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 9));
        Delete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminDelete.setBackground(new java.awt.Color(153, 51, 51));
        AdminDelete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        AdminDelete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/corendon-airlines.jpg"))); // NOI18N
        jLabel42.setText("jLabel11");
        AdminDelete.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 300, 70));

        jLabel44.setText("Zip/Postal code   :");
        AdminDelete.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 90, 20));

        jLabel46.setText("Country    :");
        AdminDelete.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 70, 20));

        jLabel47.setText("Address   :");
        AdminDelete.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 60, 20));

        jLabel48.setText("City     :");
        AdminDelete.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, -1, -1));

        jLabel49.setText("Name   :");
        AdminDelete.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, 20));

        jLabel50.setText("Email     :");
        AdminDelete.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, -1, -1));

        jTextField24.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField24.setText("Example: Egidiusstraat");
        jTextField24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField24ActionPerformed(evt);
            }
        });
        AdminDelete.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 240, -1));

        jTextField25.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField25.setText("Example: Amsterdam");
        jTextField25.setToolTipText("");
        AdminDelete.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 240, -1));

        jTextField29.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField29.setText("Example: 1055GK");
        AdminDelete.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 240, -1));

        jTextField30.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField30.setText("Example: John@corendon.com");
        AdminDelete.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 240, -1));

        jTextField31.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField31.setText("example: john");
        AdminDelete.add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 240, -1));

        jTextField32.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField32.setText("Example: The Netherlands");
        AdminDelete.add(jTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 240, -1));

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel51.setText("Account information:");
        AdminDelete.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        jLabel54.setText("Are u sure :");
        AdminDelete.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 80, 20));

        jLabel55.setText("Choose account :");
        AdminDelete.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 100, 20));

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel56.setText("Personal information:");
        AdminDelete.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Vliegtuig_CorendonNL-2-stijgend.png"))); // NOI18N
        AdminDelete.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 160, 50));

        jCheckBox1.setText("Yes");
        AdminDelete.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        jButton1.setText("Delete");
        AdminDelete.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, -1));

        jSpinner1.setModel(new javax.swing.SpinnerListModel(new String[] {"Admini1994", "Manager001", "James007", "YassineEla"}));
        jSpinner1.setToolTipText("");
        AdminDelete.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 110, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/00000001.JPG"))); // NOI18N
        jLabel10.setToolTipText("");
        jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        AdminDelete.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 450));

        Delete.add(AdminDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(Delete, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 910, 460));

        menu1.setBackground(new java.awt.Color(255, 255, 255));

        homeButton1.setBackground(new java.awt.Color(255, 255, 255));
        homeButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        homeButton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeButton1.setText("Home");
        homeButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeButton1.setOpaque(true);
        homeButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeButton1MouseExited(evt);
            }
        });

        editButton.setBackground(new java.awt.Color(255, 255, 255));
        editButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        editButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editButton.setText("Edit account");
        editButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editButton.setOpaque(true);
        editButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editButtonMouseExited(evt);
            }
        });

        createButton.setBackground(new java.awt.Color(255, 255, 255));
        createButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        createButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createButton.setText("Create account");
        createButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createButton.setOpaque(true);
        createButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                createButtonMouseExited(evt);
            }
        });

        helpButton.setBackground(new java.awt.Color(255, 255, 255));
        helpButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        helpButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        helpButton.setText("Help");
        helpButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        helpButton.setOpaque(true);
        helpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                helpButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                helpButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout menu1Layout = new javax.swing.GroupLayout(menu1);
        menu1.setLayout(menu1Layout);
        menu1Layout.setHorizontalGroup(
            menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(editButton, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
            .addComponent(createButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(helpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menu1Layout.setVerticalGroup(
            menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu1Layout.createSequentialGroup()
                .addComponent(homeButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(helpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 201, Short.MAX_VALUE))
        );

        getContentPane().add(menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 180, 178, 410));

        logoutKnop.setBackground(new java.awt.Color(147, 51, 51));
        logoutKnop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logoutKnop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutKnop.setText("LOGOUT");
        logoutKnop.setOpaque(true);
        logoutKnop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutKnopMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutKnopMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutKnopMouseExited(evt);
            }
        });
        getContentPane().add(logoutKnop, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 89, 90, 33));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/layoutCorendonFinalVeranderd.png"))); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, Background, org.jdesktop.beansbinding.ELProperty.create("${background}"), Background, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButton1MouseClicked
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(AdminHome);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_homeButton1MouseClicked

    private void homeButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButton1MouseEntered
        homeButton1.setBackground(new java.awt.Color(153,51,51));
    }//GEN-LAST:event_homeButton1MouseEntered

    private void homeButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButton1MouseExited
        homeButton1.setBackground(Color.white);
    }//GEN-LAST:event_homeButton1MouseExited

    private void editButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonMouseClicked
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(AdminEdit1);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_editButtonMouseClicked

    private void editButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonMouseEntered
        editButton.setBackground(new java.awt.Color(153,51,51));
    }//GEN-LAST:event_editButtonMouseEntered

    private void editButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonMouseExited
        editButton.setBackground(Color.white);
    }//GEN-LAST:event_editButtonMouseExited

    private void createButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createButtonMouseClicked
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(Create);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_createButtonMouseClicked

    private void createButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createButtonMouseEntered
        createButton.setBackground(new java.awt.Color(153,51,51));
    }//GEN-LAST:event_createButtonMouseEntered

    private void createButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createButtonMouseExited
        createButton.setBackground(Color.white);
    }//GEN-LAST:event_createButtonMouseExited

    private void helpButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpButtonMouseClicked
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(Help);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_helpButtonMouseClicked

    private void helpButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpButtonMouseEntered
        helpButton.setBackground(new java.awt.Color(153,51,51));
    }//GEN-LAST:event_helpButtonMouseEntered

    private void helpButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpButtonMouseExited
        helpButton.setBackground(Color.white);
    }//GEN-LAST:event_helpButtonMouseExited

    private void addressFieldEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressFieldEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressFieldEditActionPerformed

    private void homeadressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeadressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeadressActionPerformed

    private void accounttypeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accounttypeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accounttypeeActionPerformed

    private void jTextField24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField24ActionPerformed

    private void logoutKnopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutKnopMouseEntered
        logoutKnop.setBackground(new java.awt.Color(224, 90, 90));
    }//GEN-LAST:event_logoutKnopMouseEntered

    private void logoutKnopMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutKnopMouseExited
        logoutKnop.setBackground(new java.awt.Color(153, 51, 51));
    }//GEN-LAST:event_logoutKnopMouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Dbmanager dbm = new Dbmanager();
        QueryManager qm = new QueryManager(dbm);
        //open database connection
        dbm.openConnection();

        CreateAccount createaccount = new CreateAccount("",false, username1.getText(), password.getText(), accounttypee.getText(), firstname.getText(), homeadress.getText(), homecity.getText(), homepostal.getText(), homecountry.getText(), homeemail.getText());
        if ("employee".equals(createaccount.accounttype)) {
            createaccount.accounttype = "employee";
        }
        if ("Employee".equals(createaccount.accounttype)) {
            createaccount.accounttype = "employee";
        }
        if ("Manager".equals(createaccount.accounttype)) {
            createaccount.accounttype = "manager";
        }
        if ("Admin".equals(createaccount.accounttype)) {
            createaccount.accounttype = "admin";
        }
        if ("Administrator".equals(createaccount.accounttype)) {
            createaccount.accounttype = "admin";
        }
        if ("administrator".equals(createaccount.accounttype)) {
            createaccount.accounttype = "admin";
        }
        qm.insertcreateaccount(createaccount);
        Employee.infoBox("Succesfully Saved\n" + "Username:  " + username1.getText(), "Saved");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton5KeyPressed

    }//GEN-LAST:event_jButton5KeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(AdminEdit);
        jPanel1.repaint();
        jPanel1.revalidate(); 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Dbmanager dbm = new Dbmanager();
        QueryManager qm = new QueryManager(dbm);
        //open database connection
        dbm.openConnection();

        if (searchtxt.getText().equals("")) 
            {
                udl = qm.getUsers("SELECT * from createaccount");
            }else
        {
          udl = qm.getUsers("SELECT * from createaccount where username  ='" + searchtxt.getText() + "'");
        }
            DefaultListModel<String> model = new DefaultListModel<String>();

            for (CreateAccount s : udl) {
                model.addElement(s.username);
                System.out.println(s.username);
          //  userId = Integer.parseInt(s.userid);
               
              
            }
            listUsers.setModel(model);

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void username1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username1ActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
      Dbmanager dbm = new Dbmanager();
        QueryManager qm = new QueryManager(dbm);
        //open database connection
        dbm.openConnection();
     
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
         Dbmanager dbm = new Dbmanager();
        QueryManager qm = new QueryManager(dbm);
        //open database connection
        dbm.openConnection();
        qm.deleteUser(userId);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
         Dbmanager dbm = new Dbmanager();
        QueryManager qm = new QueryManager(dbm);
        //open database connection
        dbm.openConnection(); 
        qm.updateUser(jTextField7.getText(), jTextField4.getText());
    }//GEN-LAST:event_jButton8MouseClicked

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void editAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAdminButtonActionPerformed
        
    }//GEN-LAST:event_editAdminButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void password2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password2ActionPerformed

    private void logoutKnopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutKnopMouseClicked
  Login login = new Login();
        login.setVisible(true);
        this.dispose();     
    }//GEN-LAST:event_logoutKnopMouseClicked

    private void editAdminButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editAdminButtonMouseClicked
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(AdminEdit);
        jPanel1.repaint();
        jPanel1.revalidate(); 
    }//GEN-LAST:event_editAdminButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminCreate;
    private javax.swing.JPanel AdminDelete;
    private javax.swing.JPanel AdminEdit;
    private javax.swing.JPanel AdminEdit1;
    private javax.swing.JPanel AdminHelp;
    private javax.swing.JPanel AdminHome;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel BackgroundAdmin;
    private javax.swing.JPanel Create;
    private javax.swing.JPanel Delete;
    private javax.swing.JPanel Edit;
    private javax.swing.JPanel Help;
    private javax.swing.JPanel Home;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel PersonalInfoTitleEdit;
    private javax.swing.JLabel PersonalInfoTitleEdit1;
    private javax.swing.JLabel accountInfoTitleEdit;
    private javax.swing.JComboBox accounttypeDropboxEdit;
    private javax.swing.JTextField accounttypee;
    private javax.swing.JLabel accountypeEdit;
    private javax.swing.JLabel addressAdmin;
    private javax.swing.JLabel addressAdminText;
    private javax.swing.JLabel addressEdit;
    private javax.swing.JTextField addressFieldEdit;
    private javax.swing.JLabel background;
    private javax.swing.JLabel background1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cityAdmin;
    private javax.swing.JLabel cityAdminText;
    private javax.swing.JLabel cityEdit;
    private javax.swing.JTextField cityFieldEdit;
    private javax.swing.JLabel corendonTitleEdit;
    private javax.swing.JLabel corendonTitleEdit1;
    private javax.swing.JLabel countryAdmin;
    private javax.swing.JLabel countryAdminText;
    private javax.swing.JLabel countryEdit;
    private javax.swing.JTextField countryFieldEdit;
    private javax.swing.JLabel createButton;
    private javax.swing.JLabel dateAdmin;
    private javax.swing.JLabel dateAdminText;
    private javax.swing.JToggleButton editAdminButton;
    private javax.swing.JLabel editButton;
    private javax.swing.JLabel emailAdmin;
    private javax.swing.JLabel emailAdminText;
    private javax.swing.JLabel emailEdit;
    private javax.swing.JTextField emailFieldEdit;
    private javax.swing.JTextField firstname;
    private javax.swing.JLabel helpButton;
    private javax.swing.JLabel homeButton1;
    private javax.swing.JTextField homeadress;
    private javax.swing.JTextField homecity;
    private javax.swing.JTextField homecountry;
    private javax.swing.JTextField homeemail;
    private javax.swing.JTextField homepostal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JList listUsers;
    private javax.swing.JLabel logoutKnop;
    private javax.swing.JPanel menu1;
    private javax.swing.JLabel nameAdmin;
    private javax.swing.JLabel nameAdminText;
    private javax.swing.JLabel nameEdit;
    private javax.swing.JTextField nameFieldEdit;
    private javax.swing.JLabel newusernameEdit;
    private javax.swing.JTextField newusernameFieldEdit;
    private javax.swing.JLabel newwwEdit;
    private javax.swing.JTextField newwwFieldEdit;
    private javax.swing.JLabel oldwwEdit;
    private javax.swing.JTextField oldwwFieldEdit;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField password2;
    private javax.swing.JLabel postalcodeAdmin;
    private javax.swing.JLabel postalcodeAdminText;
    private javax.swing.JLabel profileAdmin;
    private javax.swing.JLabel repeatwwEdit;
    private javax.swing.JTextField repeatwwFieldEdit;
    private javax.swing.JTextField searchtxt;
    private javax.swing.JTextField username1;
    private javax.swing.JLabel usernameAdmin;
    private javax.swing.JLabel usernameAdminText;
    private javax.swing.JLabel welcomeAdmin;
    private javax.swing.JLabel zipEdit;
    private javax.swing.JTextField zipFieldEdit;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    double width = screenSize.getWidth();
    double height = screenSize.getHeight();
}
