package view;

import Connectivity.Dbmanager;
import Connectivity.QueryManager;
import java.awt.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Baggage;
import model.CreateAccount;
import model.Customerinfo;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.jdbc.JDBCPieDataset;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author EdoTyran
 */
public class Manager extends javax.swing.JFrame {

    Dbmanager dm = new Dbmanager();
    QueryManager query = new QueryManager(dm);
    ArrayList<Customerinfo> lldd = new ArrayList();

    public void SetInfo(CreateAccount createaccount) {
        LoggedIN.setText("Logged in as: " + createaccount.accounttype);
        tUsernameHome.setText(createaccount.username);
        welcomeText1.setText("Welcome " + createaccount.username + ",");
        lNameHome.setText("Not Set");
        lAddressHome.setText("Not Set");
        lDateHome.setText("Not Set");
        lCityHome.setText("Not Set");
        lPostalCodeHome.setText("Not Set");
        lCountryHome.setText("Not Set");
        lEmailHome.setText("Not Set");

        if ("employee".equals(createaccount.accounttype)) {
            setVisible(true);
        } else {
            setVisible(false);
        }
    }

    public void SetUser(CreateAccount createaccount) {

        if ("manager".equals(createaccount.accounttype)) {
            setVisible(true);
        } else {
            setVisible(false);
        }
    }

    public ArrayList<Baggage> lld = new ArrayList();
    public JTable table;
    public JFrame frame = new JFrame();
    int xMouse, yMouse;

    /**
     * Creates new form Employee
     */
    public Manager() {
        super("Lost Baggage");
        setSize(1300, 650);
        setResizable(false);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setVisible(true);
        initComponents();
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(ManagerHome);
        jPanel1.repaint();
        jPanel1.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        LoggedIN = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Graphs = new javax.swing.JPanel();
        ManagerGraphs = new javax.swing.JPanel();
        pieChart = new javax.swing.JLabel();
        barChart2W = new javax.swing.JLabel();
        barChartY = new javax.swing.JLabel();
        graphPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Home = new javax.swing.JPanel();
        ManagerHome = new javax.swing.JPanel();
        welcomeText1 = new javax.swing.JLabel();
        usernameHome = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        emailHome = new javax.swing.JLabel();
        countryHome = new javax.swing.JLabel();
        postalCodeHome = new javax.swing.JLabel();
        cityHome = new javax.swing.JLabel();
        dateHome = new javax.swing.JLabel();
        nameHome = new javax.swing.JLabel();
        addressHome = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        editHome = new javax.swing.JToggleButton();
        tUsernameHome = new javax.swing.JLabel();
        lAddressHome = new javax.swing.JLabel();
        lDateHome = new javax.swing.JLabel();
        lCityHome = new javax.swing.JLabel();
        lPostalCodeHome = new javax.swing.JLabel();
        lCountryHome = new javax.swing.JLabel();
        lEmailHome = new javax.swing.JLabel();
        lNameHome = new javax.swing.JLabel();
        Backgroundlabel1 = new javax.swing.JLabel();
        Search = new javax.swing.JPanel();
        ManagerSearch = new javax.swing.JPanel();
        searchBaggage = new javax.swing.JTextField();
        searchButtonBaggage = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        viewCustomerButton = new javax.swing.JButton();
        searchCustomer = new javax.swing.JTextField();
        searchButtonCustomer = new javax.swing.JLabel();
        viewBaggageButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Status = new javax.swing.JPanel();
        ManagerStatus = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        searchResultStatus = new javax.swing.JList();
        cFoundStatus = new javax.swing.JCheckBox();
        cFoundBaggageStatus = new javax.swing.JCheckBox();
        cHandledBaggageStatus = new javax.swing.JCheckBox();
        cOverviewStatus = new javax.swing.JCheckBox();
        searchStatus = new javax.swing.JTextField();
        searchButtonResult = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LogFiles = new javax.swing.JPanel();
        ManagerLogfiles = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        searchResultsLogFiles = new javax.swing.JList();
        cAllLogFiles = new javax.swing.JCheckBox();
        cTimeLogFiles = new javax.swing.JCheckBox();
        cUserLogFiles = new javax.swing.JCheckBox();
        searchLogFiles = new javax.swing.JTextField();
        searchButtonLogFiles = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Help = new javax.swing.JPanel();
        ManagerHelp = new javax.swing.JPanel();
        helpTitle6 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        homeButton = new javax.swing.JLabel();
        searchButton = new javax.swing.JLabel();
        StatusButton = new javax.swing.JLabel();
        LogfilesButton = new javax.swing.JLabel();
        Graphbutton = new javax.swing.JLabel();
        helpButton1 = new javax.swing.JLabel();
        logoutKnop = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lost Baggage");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoggedIN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LoggedIN.setText("Logged in as:");
        getContentPane().add(LoggedIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 150, 30));

        ID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ID.setText("Employee ID:");
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 130, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 9));
        jPanel1.setLayout(new java.awt.BorderLayout());

        Graphs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 9));
        Graphs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManagerGraphs.setBackground(new java.awt.Color(153, 51, 51));
        ManagerGraphs.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.gray, null, java.awt.Color.lightGray));
        ManagerGraphs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pieChart.setBackground(new java.awt.Color(151, 53, 53));
        pieChart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pieChart.setText("Pie chart");
        pieChart.setToolTipText("This is to show the amount of lost, found and handled bagage");
        pieChart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pieChart.setOpaque(true);
        pieChart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pieChartMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pieChartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pieChartMouseExited(evt);
            }
        });
        ManagerGraphs.add(pieChart, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 120, 30));

        barChart2W.setBackground(new java.awt.Color(151, 53, 53));
        barChart2W.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        barChart2W.setText("Bar chart 2 weeks");
        barChart2W.setToolTipText("This is to show the amount of lost, found and handled bagage");
        barChart2W.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barChart2W.setOpaque(true);
        barChart2W.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barChart2WMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                barChart2WMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                barChart2WMouseExited(evt);
            }
        });
        ManagerGraphs.add(barChart2W, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 120, 30));

        barChartY.setBackground(new java.awt.Color(151, 53, 53));
        barChartY.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        barChartY.setText("Bar chart year");
        barChartY.setToolTipText("This is to show the amount of lost, found and handled bagage");
        barChartY.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barChartY.setOpaque(true);
        barChartY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barChartYMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                barChartYMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                barChartYMouseExited(evt);
            }
        });
        ManagerGraphs.add(barChartY, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 120, 30));

        graphPanel4.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setOpaque(true);
        graphPanel4.add(jLabel1, java.awt.BorderLayout.CENTER);

        ManagerGraphs.add(graphPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 580, 290));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/corendon-airlines.jpg"))); // NOI18N
        jLabel16.setText("jLabel11");
        ManagerGraphs.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 300, 70));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setToolTipText("");
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jLabel6.setOpaque(true);
        ManagerGraphs.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 450));

        Graphs.add(ManagerGraphs, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 920, -1));

        jPanel1.add(Graphs, java.awt.BorderLayout.CENTER);

        Home.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 9));
        Home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManagerHome.setBackground(new java.awt.Color(153, 51, 51));
        ManagerHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        ManagerHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeText1.setFont(new java.awt.Font("Tahoma", 2, 30)); // NOI18N
        welcomeText1.setText("Welcome,");
        welcomeText1.setToolTipText("");
        ManagerHome.add(welcomeText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 150, 50));

        usernameHome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        usernameHome.setText("Username :");
        ManagerHome.add(usernameHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 240, 70, 20));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Vliegtuig_CorendonNL-2-stijgend.png"))); // NOI18N
        ManagerHome.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 160, 50));

        emailHome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        emailHome.setText("Email :");
        ManagerHome.add(emailHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 320, 70, 20));

        countryHome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        countryHome.setText("Country :");
        ManagerHome.add(countryHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 280, 70, 20));

        postalCodeHome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        postalCodeHome.setText("Postal code :");
        ManagerHome.add(postalCodeHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 240, 70, 20));

        cityHome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cityHome.setText("City :");
        ManagerHome.add(cityHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 200, 70, 20));

        dateHome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dateHome.setText("Date :");
        ManagerHome.add(dateHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 320, 70, 20));

        nameHome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nameHome.setText("Name :");
        ManagerHome.add(nameHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 200, 70, 20));

        addressHome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addressHome.setText("Address :");
        ManagerHome.add(addressHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 280, 70, 20));

        jLabel26.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel26.setText("Profile :");
        ManagerHome.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 90, 40));

        editHome.setText("Edit");
        editHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editHomeActionPerformed(evt);
            }
        });
        ManagerHome.add(editHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, -1, -1));

        tUsernameHome.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        tUsernameHome.setText("jLabel54");
        ManagerHome.add(tUsernameHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 90, 20));

        lAddressHome.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lAddressHome.setText("jLabel46");
        ManagerHome.add(lAddressHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 90, 20));

        lDateHome.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lDateHome.setText("jLabel46");
        ManagerHome.add(lDateHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 90, 20));

        lCityHome.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lCityHome.setText("jLabel46");
        ManagerHome.add(lCityHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 90, 20));

        lPostalCodeHome.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lPostalCodeHome.setText("jLabel46");
        ManagerHome.add(lPostalCodeHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 90, 20));

        lCountryHome.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lCountryHome.setText("jLabel46");
        ManagerHome.add(lCountryHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 90, 20));

        lEmailHome.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lEmailHome.setText("jLabel46");
        ManagerHome.add(lEmailHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 90, 20));

        lNameHome.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lNameHome.setText("jLabel46");
        ManagerHome.add(lNameHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 90, 20));

        Backgroundlabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/00000001.JPG"))); // NOI18N
        Backgroundlabel1.setToolTipText("");
        Backgroundlabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        ManagerHome.add(Backgroundlabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 490));

        Home.add(ManagerHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(Home, java.awt.BorderLayout.PAGE_START);

        Search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 9));
        Search.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManagerSearch.setBackground(new java.awt.Color(0, 0, 0));
        ManagerSearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        ManagerSearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchBaggage.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        searchBaggage.setText("Search Baggage");
        searchBaggage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBaggageActionPerformed(evt);
            }
        });
        ManagerSearch.add(searchBaggage, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 540, -1));

        searchButtonBaggage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seoLogo.png"))); // NOI18N
        searchButtonBaggage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonBaggageMouseClicked(evt);
            }
        });
        ManagerSearch.add(searchButtonBaggage, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/corendon-airlines.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        ManagerSearch.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 300, 70));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Vliegtuig_CorendonNL-2-stijgend.png"))); // NOI18N
        ManagerSearch.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 160, 50));

        viewCustomerButton.setText("View All customers");
        viewCustomerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewCustomerButtonMouseClicked(evt);
            }
        });
        viewCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCustomerButtonActionPerformed(evt);
            }
        });
        ManagerSearch.add(viewCustomerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 140, -1));

        searchCustomer.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        searchCustomer.setText("Search Customer");
        ManagerSearch.add(searchCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 540, -1));

        searchButtonCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seoLogo.png"))); // NOI18N
        searchButtonCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonCustomerMouseClicked(evt);
            }
        });
        ManagerSearch.add(searchButtonCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, -1, -1));

        viewBaggageButton.setText("View Al Baggage");
        viewBaggageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewBaggageButtonMouseClicked(evt);
            }
        });
        viewBaggageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBaggageButtonActionPerformed(evt);
            }
        });
        ManagerSearch.add(viewBaggageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 130, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/00000001.JPG"))); // NOI18N
        jLabel3.setToolTipText("");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        ManagerSearch.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 450));
        ManagerSearch.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        Search.add(ManagerSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 930, -1));

        jPanel1.add(Search, java.awt.BorderLayout.PAGE_END);

        Status.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 9));
        Status.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManagerStatus.setBackground(new java.awt.Color(153, 51, 51));
        ManagerStatus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.gray, null, java.awt.Color.lightGray));
        ManagerStatus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchResultStatus.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Baggage status" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(searchResultStatus);

        ManagerStatus.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 540, 220));

        cFoundStatus.setSelected(true);
        cFoundStatus.setText("Found");
        cFoundStatus.setToolTipText("found");
        cFoundStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cFoundStatusActionPerformed(evt);
            }
        });
        cFoundStatus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cFoundStatusKeyPressed(evt);
            }
        });
        ManagerStatus.add(cFoundStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 110, 20));

        cFoundBaggageStatus.setText("Found baggage");
        ManagerStatus.add(cFoundBaggageStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 110, -1));

        cHandledBaggageStatus.setText("Handled Baggage");
        ManagerStatus.add(cHandledBaggageStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        cOverviewStatus.setText("Overview");
        ManagerStatus.add(cOverviewStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 110, -1));

        searchStatus.setText("Search");
        ManagerStatus.add(searchStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 540, -1));

        searchButtonResult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seoLogo.png"))); // NOI18N
        searchButtonResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonResultMouseClicked(evt);
            }
        });
        ManagerStatus.add(searchButtonResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/corendon-airlines.jpg"))); // NOI18N
        jLabel13.setText("jLabel11");
        ManagerStatus.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 300, 70));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Vliegtuig_CorendonNL-2-stijgend.png"))); // NOI18N
        ManagerStatus.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 160, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/00000001.JPG"))); // NOI18N
        jLabel4.setToolTipText("");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        ManagerStatus.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 450));

        Status.add(ManagerStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 920, -1));

        jPanel1.add(Status, java.awt.BorderLayout.LINE_END);

        LogFiles.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 9));
        LogFiles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManagerLogfiles.setBackground(new java.awt.Color(153, 51, 51));
        ManagerLogfiles.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.gray, null, java.awt.Color.lightGray));
        ManagerLogfiles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchResultsLogFiles.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Log Files" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(searchResultsLogFiles);

        ManagerLogfiles.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 540, 220));

        cAllLogFiles.setText("All");
        ManagerLogfiles.add(cAllLogFiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        cTimeLogFiles.setText("Time");
        ManagerLogfiles.add(cTimeLogFiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 110, -1));

        cUserLogFiles.setText("Users");
        ManagerLogfiles.add(cUserLogFiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 110, -1));

        searchLogFiles.setText("Search");
        ManagerLogfiles.add(searchLogFiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 540, -1));

        searchButtonLogFiles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seoLogo.png"))); // NOI18N
        ManagerLogfiles.add(searchButtonLogFiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/corendon-airlines.jpg"))); // NOI18N
        jLabel15.setText("jLabel11");
        ManagerLogfiles.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 300, 70));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Vliegtuig_CorendonNL-2-stijgend.png"))); // NOI18N
        ManagerLogfiles.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 160, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/00000001.JPG"))); // NOI18N
        jLabel5.setToolTipText("");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        ManagerLogfiles.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 450));

        LogFiles.add(ManagerLogfiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 930, -1));

        jPanel1.add(LogFiles, java.awt.BorderLayout.LINE_START);

        Help.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 9));
        Help.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManagerHelp.setBackground(new java.awt.Color(153, 51, 51));
        ManagerHelp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.gray, null, java.awt.Color.lightGray));
        ManagerHelp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        helpTitle6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        helpTitle6.setText("Welkom Manager,");
        ManagerHelp.add(helpTitle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Vliegtuig_CorendonNL-2-stijgend.png"))); // NOI18N
        ManagerHelp.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 160, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/00000001.JPG"))); // NOI18N
        jLabel7.setToolTipText("");
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        ManagerHelp.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 450));

        Help.add(ManagerHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 920, -1));

        jPanel1.add(Help, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 910, 460));

        menu.setBackground(new java.awt.Color(255, 255, 255));

        homeButton.setBackground(new java.awt.Color(255, 255, 255));
        homeButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        homeButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeButton.setText("Home");
        homeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeButton.setOpaque(true);
        homeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeButtonMouseExited(evt);
            }
        });

        searchButton.setBackground(new java.awt.Color(255, 255, 255));
        searchButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchButton.setText("Search");
        searchButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchButton.setOpaque(true);
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchButtonMouseExited(evt);
            }
        });

        StatusButton.setBackground(new java.awt.Color(255, 255, 255));
        StatusButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        StatusButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StatusButton.setText("Status");
        StatusButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StatusButton.setOpaque(true);
        StatusButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StatusButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StatusButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StatusButtonMouseExited(evt);
            }
        });

        LogfilesButton.setBackground(new java.awt.Color(255, 255, 255));
        LogfilesButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LogfilesButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogfilesButton.setText("Log files");
        LogfilesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogfilesButton.setOpaque(true);
        LogfilesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogfilesButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogfilesButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogfilesButtonMouseExited(evt);
            }
        });

        Graphbutton.setBackground(new java.awt.Color(255, 255, 255));
        Graphbutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Graphbutton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Graphbutton.setText("Graphs");
        Graphbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Graphbutton.setOpaque(true);
        Graphbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GraphbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GraphbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GraphbuttonMouseExited(evt);
            }
        });

        helpButton1.setBackground(new java.awt.Color(255, 255, 255));
        helpButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        helpButton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        helpButton1.setText("Help");
        helpButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        helpButton1.setOpaque(true);
        helpButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                helpButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                helpButton1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
            .addComponent(StatusButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LogfilesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Graphbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(helpButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(homeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(StatusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(LogfilesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(Graphbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(helpButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 180, 178, 320));

        logoutKnop.setBackground(new java.awt.Color(147, 51, 51));
        logoutKnop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logoutKnop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutKnop.setText("LOGOUT");
        logoutKnop.setOpaque(true);
        logoutKnop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutKnopMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutKnopMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutKnopMouseExited(evt);
            }
        });
        getContentPane().add(logoutKnop, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 89, 90, 33));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/layoutCorendonFinalVeranderd.png"))); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, Background, org.jdesktop.beansbinding.ELProperty.create("${background}"), Background, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseEntered
        homeButton.setBackground(new java.awt.Color(151,53,53));
    }//GEN-LAST:event_homeButtonMouseEntered

    private void homeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseExited
        homeButton.setBackground(Color.white);
    }//GEN-LAST:event_homeButtonMouseExited

    private void searchButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseEntered
        searchButton.setBackground(new java.awt.Color(151,53,53));
    }//GEN-LAST:event_searchButtonMouseEntered

    private void StatusButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StatusButtonMouseEntered
        StatusButton.setBackground(new java.awt.Color(151,53,53));
    }//GEN-LAST:event_StatusButtonMouseEntered

    private void LogfilesButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogfilesButtonMouseEntered
        LogfilesButton.setBackground(new java.awt.Color(151,53,53));
    }//GEN-LAST:event_LogfilesButtonMouseEntered

    private void GraphbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GraphbuttonMouseEntered
        Graphbutton.setBackground(new java.awt.Color(151,53,53));
    }//GEN-LAST:event_GraphbuttonMouseEntered

    private void searchButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseExited
        searchButton.setBackground(Color.white);
    }//GEN-LAST:event_searchButtonMouseExited

    private void StatusButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StatusButtonMouseExited
        StatusButton.setBackground(Color.white);
    }//GEN-LAST:event_StatusButtonMouseExited

    private void LogfilesButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogfilesButtonMouseExited
        LogfilesButton.setBackground(Color.white);
    }//GEN-LAST:event_LogfilesButtonMouseExited

    private void GraphbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GraphbuttonMouseExited
        Graphbutton.setBackground(Color.white);
    }//GEN-LAST:event_GraphbuttonMouseExited

    private void helpButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpButton1MouseEntered
        helpButton1.setBackground(new java.awt.Color(151,53,53));
    }//GEN-LAST:event_helpButton1MouseEntered

    private void helpButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpButton1MouseExited
        helpButton1.setBackground(Color.white);
    }//GEN-LAST:event_helpButton1MouseExited

    private void homeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseClicked
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(ManagerHome);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_homeButtonMouseClicked

    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseClicked
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(Search);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_searchButtonMouseClicked

    private void StatusButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StatusButtonMouseClicked
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(Status);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_StatusButtonMouseClicked

    private void LogfilesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogfilesButtonMouseClicked
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(LogFiles);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_LogfilesButtonMouseClicked

    private void GraphbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GraphbuttonMouseClicked
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(Graphs);
        jPanel1.repaint();
        jPanel1.revalidate();
        
        try {
            Connection connection;
            Class.forName("com.mysql.jdbc.Driver");

            String url = "jdbc:mysql://localhost:3306/fys?zeroDateTimeBehavior=convertToNull";
            String user = "root", pass = "";
            System.out.println("Connected");

            /**
             * Open connection
             */
            connection = DriverManager.getConnection(url, user, pass);
//            Dbmanager dbm = new Dbmanager();
//            QueryManager qm = new QueryManager(dbm);
//            //Open database connection
//            dbm.openConnection();
            
            String query = "SELECT status, count(*) FROM baggage GROUP BY status";
//            DefaultPieDataset pieDataset = new DefaultPieDataset(query);
            JDBCPieDataset pieDataset = new JDBCPieDataset(connection, query);
            
            JFreeChart pieChartDb = ChartFactory.createPieChart3D("foundLostHandledChart", pieDataset, true, true, false);
            
            PiePlot3D p = (PiePlot3D)pieChartDb.getPlot();
            p.setForegroundAlpha(0.5f);
            ChartPanel frame1 = new ChartPanel(pieChartDb);
        
            graphPanel4.removeAll();
            graphPanel4.revalidate();
            graphPanel4.add(frame1);
            graphPanel4.repaint();
            graphPanel4.revalidate();
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_GraphbuttonMouseClicked

    private void helpButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpButton1MouseClicked
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(Help);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_helpButton1MouseClicked

    private void logoutKnopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutKnopMouseEntered
        logoutKnop.setBackground(new java.awt.Color(224, 90, 90));
    }//GEN-LAST:event_logoutKnopMouseEntered

    private void logoutKnopMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutKnopMouseExited
        logoutKnop.setBackground(new java.awt.Color(153, 51, 51));
    }//GEN-LAST:event_logoutKnopMouseExited

    private void searchButtonBaggageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonBaggageMouseClicked
        Dbmanager dbm = new Dbmanager();
        QueryManager qm = new QueryManager(dbm);
        //Open database connection

        dbm.openConnection();

        if (searchBaggage.getText().equals("")) {
            lld = qm.getBaggage("SELECT * from baggage");
        } else {
            lld = qm.getBaggage("SELECT * FROM baggage WHERE baggageId = " + searchBaggage.getText());
        }

        DefaultTableModel model = new DefaultTableModel();
        table = new JTable(model);

        // Create a couple of columns 
        model.addColumn("Baggageid");
        model.addColumn("color");
        model.addColumn("weight");
        model.addColumn("department");
        model.addColumn("material");
        model.addColumn("status");
        // Append a row 

        for (Baggage ld : lld) {
            model.addRow(new Object[]{
                ld.baggageId, ld.description, ld.collor, ld.weight, ld.department, ld.materials, ld.status
            });
        }
        Container contentPane = this.getContentPane();
        contentPane.setLayout(new BorderLayout());
        contentPane.setSize(700, 500);
        contentPane.setBounds(200, 20, 700, 500);
        table.setSize(300, 150);
        JScrollPane jScrollPane1 = new JScrollPane(table);
        jScrollPane1.setSize(700, 500);
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(jScrollPane1);
        jPanel1.repaint();
        jPanel1.revalidate();

        jScrollPane1 = new JScrollPane(table);
        frame.add(jScrollPane1, BorderLayout.CENTER);
        frame.setSize(700, 500);
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
      
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(ManagerSearch);
        jPanel1.repaint();
        jPanel1.revalidate();


    }//GEN-LAST:event_searchButtonBaggageMouseClicked

    private void viewCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCustomerButtonActionPerformed
        Dbmanager dbm = new Dbmanager();
        QueryManager qm = new QueryManager(dbm);
        //Open database connection

        dbm.openConnection();

        if (searchBaggage.getText().equals("")) {
            lld = qm.getBaggage("SELECT * from baggage");
        } else {
            lld = qm.getBaggage("SELECT * FROM baggage WHERE baggageId = " + searchBaggage.getText());
        }

        DefaultTableModel model = new DefaultTableModel();
        table = new JTable(model);

        // Create a couple of columns 
        model.addColumn("Baggageid");
        model.addColumn("color");
        model.addColumn("weight");
        model.addColumn("department");
        model.addColumn("material");
        model.addColumn("status");
        // Append a row 

        for (Baggage ld : lld) {
            model.addRow(new Object[]{
                ld.baggageId, ld.description, ld.collor, ld.weight, ld.department, ld.materials, ld.status
            });
        }
        Container contentPane = this.getContentPane();
        contentPane.setLayout(new BorderLayout());
        contentPane.setSize(700, 500);
        contentPane.setBounds(200, 20, 700, 500);
        table.setSize(300, 150);
        JScrollPane jScrollPane1 = new JScrollPane(table);
        jScrollPane1.setSize(700, 500);
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(jScrollPane1);
        jPanel1.repaint();
        jPanel1.revalidate();

        jScrollPane1 = new JScrollPane(table);
        frame.add(jScrollPane1, BorderLayout.CENTER);
        frame.setSize(700, 500);
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(ManagerSearch);
        jPanel1.repaint();
        jPanel1.revalidate();

    }//GEN-LAST:event_viewCustomerButtonActionPerformed

    private void logoutKnopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutKnopMouseClicked
        Login login = new Login();
        login.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_logoutKnopMouseClicked

    private void searchButtonResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonResultMouseClicked
        Dbmanager dbm = new Dbmanager();
        QueryManager qm = new QueryManager(dbm);
        //Open database connection

        dbm.openConnection();

        if (searchStatus.getText().equals("")) {
            lld = qm.getBaggage("SELECT * from baggage");

        } else if (cFoundStatus.getText().equals("lost")) {
            lld = qm.getBaggage("SELECT * FROM baggage WHERE status = " + cFoundStatus.getText());
        }

        DefaultTableModel model = new DefaultTableModel();
        table = new JTable(model);

        // Create a couple of columns 
        model.addColumn("Baggageid");
        model.addColumn("color");
        model.addColumn("weight");
        model.addColumn("department");
        model.addColumn("material");
        model.addColumn("status");

        // Append a row 
        for (Baggage ld : lld) {
            model.addRow(new Object[]{
                ld.baggageId, ld.collor, ld.weight, ld.department, ld.materials, ld.status
            });
        }
        Container contentPane = this.getContentPane();
        contentPane.setLayout(new BorderLayout());
        contentPane.setSize(700, 500);
        contentPane.setBounds(200, 20, 700, 500);
        table.setSize(300, 150);
        JScrollPane jScrollPane1 = new JScrollPane(table);
        jScrollPane1.setSize(700, 500);
        Button a = new Button("HI");
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(jScrollPane1);
        jPanel1.repaint();
        jPanel1.revalidate();

        jScrollPane1 = new JScrollPane(table);
        frame.add(jScrollPane1, BorderLayout.CENTER);
        frame.setSize(700, 500);
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(ManagerStatus);
        jPanel1.repaint();
        jPanel1.revalidate();

    }//GEN-LAST:event_searchButtonResultMouseClicked

    private void searchButtonCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonCustomerMouseClicked
        Dbmanager dbm = new Dbmanager();
        QueryManager qm = new QueryManager(dbm);
        //Open database connection
        dbm.openConnection();
        Customerinfo cm = new Customerinfo("", "", "", "", "", "", "");;

        //AANROEPEN qm.something
        frame = new JFrame();

        DefaultTableModel model = new DefaultTableModel();
        table = new JTable(model);

        // Create a couple of columns 
        model.addColumn("Customer Name");
        model.addColumn("Adress");
        model.addColumn("Shipping Adress");
        model.addColumn("City");
        model.addColumn("Postal");
        model.addColumn("Country");
        model.addColumn("Email");

        // Append a row 
        if (jLabel5.getText().equals("Search Baggage")) {
            lldd = qm.getCustomersinfoo("SELECT * from customerinfo");
        } else {
            lldd = qm.getCustomersinfoo("SELECT * FROM customerinfo WHERE name = '" + searchCustomer.getText() + "'"
                    + "OR lastname ='" + searchCustomer.getText() + "';");
        }

        for (Customerinfo cmm : lldd) {
            model.addRow(new Object[]{
                cmm.Name, cmm.Adress, cmm.shippingAdress, cmm.City, cmm.Postal, cmm.Country, cmm.Email});

        }

        jScrollPane1 = new JScrollPane(table);
        frame.add(jScrollPane1, BorderLayout.CENTER);
        frame.setSize(1500, 200);
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(ManagerSearch);
        jPanel1.repaint();
        jPanel1.revalidate();


    }//GEN-LAST:event_searchButtonCustomerMouseClicked

    private void cFoundStatusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cFoundStatusKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cFoundStatusKeyPressed

    private void cFoundStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cFoundStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cFoundStatusActionPerformed

    private void searchBaggageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBaggageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBaggageActionPerformed

    private void viewBaggageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBaggageButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewBaggageButtonActionPerformed

    private void viewCustomerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewCustomerButtonMouseClicked
        Dbmanager dbm = new Dbmanager();
        QueryManager qm = new QueryManager(dbm);
        //Open database connection
        dbm.openConnection();
        Customerinfo cm = new Customerinfo("", "", "", "", "", "", "");;

        //AANROEPEN qm.something
        frame = new JFrame();

        DefaultTableModel model = new DefaultTableModel();
        table = new JTable(model);

        // Create a couple of columns 
        model.addColumn("Customer Name");
        model.addColumn("Adress");
        model.addColumn("Shipping Adress");
        model.addColumn("City");
        model.addColumn("Postal");
        model.addColumn("Country");
        model.addColumn("Email");

        // Append a row 
        if (jLabel5.getText().equals("Search Customer")) {
            lldd = qm.getCustomersinfoo("SELECT * from customerinfo");
        } else {
            lldd = qm.getCustomersinfoo("SELECT * FROM customerinfo");
        }
        for (Customerinfo cmm : lldd) {
            model.addRow(new Object[]{
                cmm.Name, cmm.Adress, cmm.shippingAdress, cmm.City, cmm.Postal, cmm.Country, cmm.Email});

        }

        jScrollPane1 = new JScrollPane(table);
        frame.add(jScrollPane1, BorderLayout.CENTER);
        frame.setSize(1500, 200);
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(ManagerSearch);
        jPanel1.repaint();
        jPanel1.revalidate();


    }//GEN-LAST:event_viewCustomerButtonMouseClicked

    private void viewBaggageButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewBaggageButtonMouseClicked
        Dbmanager dbm = new Dbmanager();
        QueryManager qm = new QueryManager(dbm);
        //Open database connection

        dbm.openConnection();

        if (searchBaggage.getText().equals("Search Baggage")) {
            lld = qm.getBaggage("SELECT * from baggage");
        } else {
            lld = qm.getBaggage("SELECT * FROM baggage ");
        }

        DefaultTableModel model = new DefaultTableModel();
        table = new JTable(model);

        // Create a couple of columns 
        model.addColumn("Baggageid");
        model.addColumn("color");
        model.addColumn("weight");
        model.addColumn("department");
        model.addColumn("material");
        model.addColumn("status");
        // Append a row 

        for (Baggage ld : lld) {
            model.addRow(new Object[]{
                ld.baggageId, ld.description, ld.collor, ld.weight, ld.department, ld.materials, ld.status
            });
        }
        Container contentPane = this.getContentPane();
        contentPane.setLayout(new BorderLayout());
        contentPane.setSize(700, 500);
        contentPane.setBounds(200, 20, 700, 500);
        table.setSize(300, 150);
        JScrollPane jScrollPane1 = new JScrollPane(table);
        jScrollPane1.setSize(700, 500);
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(jScrollPane1);
        jPanel1.repaint();
        jPanel1.revalidate();

        jScrollPane1 = new JScrollPane(table);
        frame.add(jScrollPane1, BorderLayout.CENTER);
        frame.setSize(700, 500);
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);

        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(ManagerSearch);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_viewBaggageButtonMouseClicked

    private void editHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editHomeActionPerformed
        Employee.infoBox("No Permission, \nContact Administrator: \nEdo Tijoe ", "Error");
    }//GEN-LAST:event_editHomeActionPerformed

    private void pieChartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pieChartMouseEntered
        pieChart.setBackground(new java.awt.Color(224,90,90));
    }//GEN-LAST:event_pieChartMouseEntered

    private void pieChartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pieChartMouseExited
        pieChart.setBackground(new java.awt.Color(151,53,53));
    }//GEN-LAST:event_pieChartMouseExited

    private void pieChartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pieChartMouseClicked
        JFreeChart pieChartDb = ChartFactory.createPieChart3D("foundLostHandledChart", query.pieChart(), true, true, false);
            
        PiePlot3D p = (PiePlot3D)pieChartDb.getPlot();
        p.setForegroundAlpha(0.5f);
        ChartPanel frame1 = new ChartPanel(pieChartDb);
        
        graphPanel4.removeAll();
        graphPanel4.revalidate();
        graphPanel4.add(frame1);
        graphPanel4.repaint();
        graphPanel4.revalidate();
    }//GEN-LAST:event_pieChartMouseClicked

    private void barChart2WMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barChart2WMouseClicked
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        
        for (int i = 1; i < 15; i++){
            String strI = "" + i;
            dataset.setValue(i, "Lost", strI);
        }
        
        JFreeChart barChart = ChartFactory.createBarChart3D("Bagage verloren", "Verloren bagage", "Dag", dataset, PlotOrientation.VERTICAL, false, true, false);
        
        CategoryPlot p = barChart.getCategoryPlot();
        p.setForegroundAlpha(0.5f);
        ChartPanel frame1 = new ChartPanel(barChart);
        
        graphPanel4.removeAll();
        graphPanel4.revalidate();
        graphPanel4.add(frame1);
        graphPanel4.repaint();
        graphPanel4.revalidate();
    }//GEN-LAST:event_barChart2WMouseClicked

    private void barChart2WMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barChart2WMouseEntered
        barChart2W.setBackground(new java.awt.Color(224,90,90));
    }//GEN-LAST:event_barChart2WMouseEntered

    private void barChart2WMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barChart2WMouseExited
        barChart2W.setBackground(new java.awt.Color(151,53,53));
    }//GEN-LAST:event_barChart2WMouseExited

    private void barChartYMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barChartYMouseClicked
        int[] aantalLost = new int[11];
        try{
        Connection connection;
            Class.forName("com.mysql.jdbc.Driver");

            String url = "jdbc:mysql://localhost:3306/fys?zeroDateTimeBehavior=convertToNull";
            String user = "root", pass = "";
            System.out.println("Connected");
            
            String query = "SELECT status, count(*) FROM baggage GROUP BY status";
        
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        
        dataset.setValue(43, "Lost", "Jan");
        dataset.setValue(34, "Lost", "Feb");
        dataset.setValue(82, "Lost", "Mar");
        dataset.setValue(60, "Lost", "Apr");
        dataset.setValue(33, "Lost", "May");
        dataset.setValue(10, "Lost", "Jun");
        dataset.setValue(90, "Lost", "Jul");        
        dataset.setValue(52, "Lost", "Aug");        
        dataset.setValue(23, "Lost", "Sep");
        dataset.setValue(70, "Lost", "Oct");
        dataset.setValue(54, "Lost", "Nov");
        dataset.setValue(40, "Lost", "Dec");
        
        JFreeChart barChart = ChartFactory.createBarChart3D("Bagage verloren", "Verloren bagage", "Maand", dataset, PlotOrientation.VERTICAL, false, true, false);
        
        CategoryPlot p = barChart.getCategoryPlot();
        p.setForegroundAlpha(0.5f);
        ChartPanel frame1 = new ChartPanel(barChart);
        
        graphPanel4.removeAll();
        graphPanel4.revalidate();
        graphPanel4.add(frame1);
        graphPanel4.repaint();
        graphPanel4.revalidate();
        
    }//GEN-LAST:event_barChartYMouseClicked

    private void barChartYMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barChartYMouseEntered
        barChartY.setBackground(new java.awt.Color(224,90,90));
    }//GEN-LAST:event_barChartYMouseEntered

    private void barChartYMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barChartYMouseExited
        barChartY.setBackground(new java.awt.Color(151,53,53));
    }//GEN-LAST:event_barChartYMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Backgroundlabel1;
    private javax.swing.JLabel Graphbutton;
    private javax.swing.JPanel Graphs;
    private javax.swing.JPanel Help;
    private javax.swing.JPanel Home;
    private javax.swing.JLabel ID;
    private javax.swing.JPanel LogFiles;
    private javax.swing.JLabel LogfilesButton;
    private javax.swing.JLabel LoggedIN;
    private javax.swing.JPanel ManagerGraphs;
    private javax.swing.JPanel ManagerHelp;
    private javax.swing.JPanel ManagerHome;
    private javax.swing.JPanel ManagerLogfiles;
    private javax.swing.JPanel ManagerSearch;
    private javax.swing.JPanel ManagerStatus;
    private javax.swing.JPanel Search;
    private javax.swing.JPanel Status;
    private javax.swing.JLabel StatusButton;
    private javax.swing.JLabel addressHome;
    private javax.swing.JLabel barChart2W;
    private javax.swing.JLabel barChartY;
    private javax.swing.JCheckBox cAllLogFiles;
    private javax.swing.JCheckBox cFoundBaggageStatus;
    private javax.swing.JCheckBox cFoundStatus;
    private javax.swing.JCheckBox cHandledBaggageStatus;
    private javax.swing.JCheckBox cOverviewStatus;
    private javax.swing.JCheckBox cTimeLogFiles;
    private javax.swing.JCheckBox cUserLogFiles;
    private javax.swing.JLabel cityHome;
    private javax.swing.JLabel countryHome;
    private javax.swing.JLabel dateHome;
    private javax.swing.JToggleButton editHome;
    private javax.swing.JLabel emailHome;
    private javax.swing.JPanel graphPanel4;
    private javax.swing.JLabel helpButton1;
    private javax.swing.JLabel helpTitle6;
    private javax.swing.JLabel homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lAddressHome;
    private javax.swing.JLabel lCityHome;
    private javax.swing.JLabel lCountryHome;
    private javax.swing.JLabel lDateHome;
    private javax.swing.JLabel lEmailHome;
    private javax.swing.JLabel lNameHome;
    private javax.swing.JLabel lPostalCodeHome;
    private javax.swing.JLabel logoutKnop;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel nameHome;
    private javax.swing.JLabel pieChart;
    private javax.swing.JLabel postalCodeHome;
    private javax.swing.JTextField searchBaggage;
    private javax.swing.JLabel searchButton;
    private javax.swing.JLabel searchButtonBaggage;
    private javax.swing.JLabel searchButtonCustomer;
    private javax.swing.JLabel searchButtonLogFiles;
    private javax.swing.JLabel searchButtonResult;
    private javax.swing.JTextField searchCustomer;
    private javax.swing.JTextField searchLogFiles;
    private javax.swing.JList searchResultStatus;
    private javax.swing.JList searchResultsLogFiles;
    private javax.swing.JTextField searchStatus;
    private javax.swing.JLabel tUsernameHome;
    private javax.swing.JLabel usernameHome;
    private javax.swing.JButton viewBaggageButton;
    private javax.swing.JButton viewCustomerButton;
    private javax.swing.JLabel welcomeText1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    double width = screenSize.getWidth();
    double height = screenSize.getHeight();
}
